### PR TITLE
Lumi from config files instead of from AnaSamples

### PR DESCRIPTION
**Pull request by jsw-fnal**
This includes a lot more changes than just the title suggests.  To merge this, we'll need to bring most of the code back into the original state, discarding the changes I've made to turn this code to my QCD-study purposes.  But now that it is in a branch and we have a PR open, it should be easier to check out a separate copy and work from there.

### CODE REVIEW

**Comment by jsw-fnal** [comment]
I've merged master back in to my branch, keeping only the changes directly related to the lumi issue.  I think the PR is ready for testing by someone other than me now.

**Comment by caleb-james-smith** [comment]
Thanks @jsw-fnal . Can you post an example of your command to submit condor jobs? I think this PR will require me to update my config files to [2.9.3](https://github.com/susy2015/StopCfg/releases/tag/PostProcessed_StopNtuple_V2.9.3) and update my condor submission command.

Here is what I am using for 2018_AB.
```
python condorSubmit.py -d Data_EGamma_2018_PeriodsAB,Data_SingleMuon_2018_PeriodsAB,DYJetsToLL_2018,SingleTopZinv_2018,Rare_2018,TTZ_2018,Diboson_2018,GJets_2018,QCD_Photon_2018,WJetsToLNu_2018,TTbar_2018,tW_2018,ZJetsToNuNu_2018 -n 2 -y 2018_AB
```

With your update we will use pre and post HEM for data instead of periods AB and CD. Do you provide the lumi to condorSubmit.py?

**Comment by jsw-fnal** [comment]
@caleb-james-smith , Here is what I do to submit:
```
period="_PostHEM"; year=2018; python condorSubmit.py -d Data_MET_${year}${period},TTbar_${year},WJetsToLNu_${year},ZJetsToNuNu_${year},Rare_${year},QCD_${year} -n 1 -y ${year}${period} -r Data_MET_${year}${period}
```
Expanding the shell variables, that becomes
```
python condorSubmit.py -d Data_MET_2018_PostHEM,TTbar_2018,WJetsToLNu_2018,ZJetsToNuNu_2018,Rare_2018,QCD_2018 -n 1 -y 2018_PostHEM -r Data_MET_2018_PostHEM
```

The `-r` flag to `condorSubmit.py` (which has been there for a while) declares which data sample's luminosity should be used.  It then pulls the luminosity for that data sample out of the `StopCfg` files and passes that luminosity to `makePlots` using the `-L` flag.

**Comment by caleb-james-smith** [comment]
Ok, thanks. I have not used the "-r" flag, but your use makes sense.

**Comment by caleb-james-smith** [comment]
Do you know if the luminosity of "Data_MET_2018_PostHEM" is the sum of the lumis from the datasets?

**Pull request merged**
