### PR TITLE
Systematics json gen

### PR DESCRIPTION
**Pull request by arosado1**
add systematicsJsonGen.py

### CODE REVIEW

**Comment by caleb-james-smith** [comment]
thanks

**Comment by caleb-james-smith** [comment]
Here are some comments:
- Move systematicsJsonGen.py to python directory
- Use json library to write json file
- Put csv content into a csv file

**Comment by caleb-james-smith** [comment]
The script systematicsJsonGen.py is looking nice :)

**Comment by caleb-james-smith** [comment]
Ok, more picky comments... I do like systematicsJsonGen.py being in the python directory, but can we put the json and csv files in the Tools directory? Then you can run the script from the Tools directory with 
```
python python/systematicsJsonGen.py
```

**Comment by caleb-james-smith** [comment]
Also, we could get the dictionary keys from the first row to be fancy.

**Comment by arosado1** [comment]
" we could get the dictionary keys from the first row to be fancy.", what?

**Comment by caleb-james-smith** [comment]
The first row (the headers) can be the keys of the dictionary. :)

**Pull request merged**
